name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Stuff added as it is needed?
      JOB_NAME: foo
      BUILD_NUMBER: bar
      WORKSPACE: /home/runner/work/addshore/wmf-gha
      # ENV taken from https://integration.wikimedia.org/ci/job/wmf-quibble-selenium-php72-docker/139752/parameters/
      BASE_LOG_PATH: 91/769091/1
      ZUUL_PIPELINE: test
      ZUUL_UUID: a5aae79f15834b8e9521e13b1a73f727
      LOG_PATH: 91/769091/1/test/wmf-quibble-selenium-php72-docker/a5aae79
      ZUUL_VOTING: 1
      EXT_DEPENDENCIES: mediawiki/extensions/AbuseFilter\nmediawiki/extensions/AntiSpoof\nmediawiki/extensions/Babel\nmediawiki/extensions/BetaFeatures\nmediawiki/extensions/CheckUser\nmediawiki/extensions/CirrusSearch\nmediawiki/extensions/Cite\nmediawiki/extensions/CiteThisPage\nmediawiki/extensions/CodeEditor\nmediawiki/extensions/ConfirmEdit\nmediawiki/extensions/ContentTranslation\nmediawiki/extensions/Disambiguator\nmediawiki/extensions/Echo\nmediawiki/extensions/Elastica\nmediawiki/extensions/EventBus\nmediawiki/extensions/EventLogging\nmediawiki/extensions/EventStreamConfig\nmediawiki/extensions/FileImporter\nmediawiki/extensions/Flow\nmediawiki/extensions/Gadgets\nmediawiki/extensions/GeoData\nmediawiki/extensions/GlobalCssJs\nmediawiki/extensions/GlobalPreferences\nmediawiki/extensions/Graph\nmediawiki/extensions/GrowthExperiments\nmediawiki/extensions/GuidedTour\nmediawiki/extensions/ImageMap\nmediawiki/extensions/InputBox\nmediawiki/extensions/Interwiki\nmediawiki/extensions/JsonConfig\nmediawiki/extensions/Kartographer\nmediawiki/extensions/Math\nmediawiki/extensions/MobileApp\nmediawiki/extensions/MobileFrontend\nmediawiki/extensions/NavigationTiming\nmediawiki/extensions/PageImages\nmediawiki/extensions/PageViewInfo\nmediawiki/extensions/ParserFunctions\nmediawiki/extensions/PdfHandler\nmediawiki/extensions/Poem\nmediawiki/extensions/ProofreadPage\nmediawiki/extensions/SandboxLink\nmediawiki/extensions/Scribunto\nmediawiki/extensions/SiteMatrix\nmediawiki/extensions/SpamBlacklist\nmediawiki/extensions/TemplateData\nmediawiki/extensions/Thanks\nmediawiki/extensions/TimedMediaHandler\nmediawiki/extensions/Translate\nmediawiki/extensions/UniversalLanguageSelector\nmediawiki/extensions/VisualEditor\nmediawiki/extensions/WikiEditor\nmediawiki/extensions/Wikibase\nmediawiki/extensions/WikibaseCirrusSearch\nmediawiki/extensions/WikibaseMediaInfo\nmediawiki/extensions/WikimediaMessages\nmediawiki/extensions/cldr
      ZUUL_CHANGE_IDS: 769091,1
      ZUUL_PATCHSET: 1
      ZUUL_BRANCH: master
      MW_COMPOSER_MERGE_MW_IN_VENDOR: 1
      ZUUL_REF: refs/zuul/master/Zfedb00722d874f9ba3b60049707c2ced
      ZUUL_COMMIT: ffe9eb816146cde99bde7dca4ce172a25a1715ae
      SKIN_DEPENDENCIES: mediawiki/skins/MinervaNeue\nmediawiki/skins/Vector
      ZUUL_URL: git://contint2001.wikimedia.org
      ZUUL_CHANGE: 769091
      ZUUL_CHANGES: mediawiki/core:master:refs/changes/91/769091/1
      ZUUL_PROJECT: mediawiki/core

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

# Scripts taken from "Build" seciond of https://integration.wikimedia.org/ci/job/wmf-quibble-selenium-php72-docker/configure

      - name: setup cache dir
        run: |
          mkdir -m 2777 -p cache

      - name: load cached things
        run: |
          set -eux
          set -o pipefail
          exec docker run --volume "$(pwd)"/cache:/cache \
          --security-opt seccomp=unconfined \
          --init \
          --rm \
          --label "jenkins.job=$JOB_NAME" \
          --label "jenkins.build=$BUILD_NUMBER" \
          --env-file <(/usr/bin/env|egrep -v '^(HOME|SHELL|PATH|LOGNAME|MAIL)=') \
          'docker-registry.wikimedia.org/releng/castor:0.2.4' load

      - name: make log dir
        run: |
          set -eux
          mkdir -m 2777 -p "log"

#       - name: something?
#         run: |
#           set -eux
#           set -o pipefail
#           exec docker run --user=nobody --volume "$WORKSPACE":/workspace --entrypoint=/usr/bin/find \
#             --security-opt seccomp=unconfined \
#             --init \
#             --rm \
#             --label "jenkins.job=$JOB_NAME" \
#             --label "jenkins.build=$BUILD_NUMBER" \
#             --env-file <(/usr/bin/env|egrep -v '^(HOME|SHELL|PATH|LOGNAME|MAIL)=') \
#             'docker-registry.wikimedia.org/wikimedia-buster:latest' "/workspace/log" -mindepth 1 -delete

      - name: quibble
        run: |
          set -eux
          set -o pipefail
          exec docker run --entrypoint=quibble-with-apache --tmpfs /workspace/db:size=320M --volume "$(pwd)"/src:/workspace/src --volume "$(pwd)"/cache:/cache --volume "$(pwd)"/log:/workspace/log --volume /srv/git:/srv/git:ro \
            --security-opt seccomp=unconfined \
            --init \
            --rm \
            --label "jenkins.job=$JOB_NAME" \
            --label "jenkins.build=$BUILD_NUMBER" \
            --env-file <(/usr/bin/env|egrep -v '^(HOME|SHELL|PATH|LOGNAME|MAIL)=') \
            'docker-registry.wikimedia.org/releng/quibble-buster-php72:1.4.3' --packages-source "vendor" --db "mysql" --db-dir /workspace/db --git-parallel=8 --run selenium --parallel-npm-install

      - name: check output
        run: |
          set -eu

          ERROR_FILES=( mw-dberror.log mw-error.log )
          echo "Asserting empty files: ${ERROR_FILES[*]}"
          log_files="$( cd "$WORKSPACE/log"; ls "${ERROR_FILES[@]}" 2> /dev/null || :)"
          if [ ! "$log_files" ]; then
              echo "No error files created by MediaWiki. GOOD"
              exit 0
          fi
          echo "Dumping file(s) $log_files"
          set +e
              # Use `grep --color . file list` to ensure that file names appear next
              # to log messages
              (cd "$WORKSPACE/log"; grep --color . "${ERROR_FILES[@]}" 2> /dev/null)
          set -e
          echo -e "MediaWiki emitted some errors. Check output above."
          exit 1
